# Problem 1

In [ ]:
import numpy as np
from spatialmath.base import skew
#define function that takes angular velocity and timestep to produce quaternion

def fw_step(ang_vel,t): #ang_vel must be shape (1, 3)
    if ang_vel.shape != (1, 3):
        raise ValueError(f"Expected angular velocity shape (1, 3), got {ang_vel.shape}")

    #construct the omega Matrix
    omegaM = np.block([
    [0                     ,                 -ang_vel],
    [ang_vel.reshape(3, -1),           -skew(ang_vel)]
    ])

    #extract the angle from current quaternion

    #compute closed form exponential

    #construct updated quaternion
    
    np.exp(-0.5*omegaM*t)
    return omegaM


test_w = np.array([[1,0,0]])

print(test_w.shape)
print(test_w.reshape(3,-1).shape)
print(skew(test_w).shape)

print(fw_step(test_w,1))


(1, 3)
(3, 1)
(3, 3)
[[ 0 -1  0  0]
 [ 1  0  0  0]
 [ 0  0  0  1]
 [ 0  0 -1  0]]
